#cloud-config

# Add users to the system. Users are added after groups are added.
users:
  - default

write_files:
  # Apt repository for Kubernetes stuff
  - content: |
      deb http://apt.kubernetes.io/ kubernetes-xenial main
    path: /etc/apt/sources.list.d/kubernetes.list
  # Create Post install Shell Script
  - content: |
      cd ~/src
      sudo chsh -s /usr/bin/zsh ubuntu

      # Step 1: Install oh-my-zsh
      cd ~/src
      sudo /usr/bin/chsh -s /usr/bin/zsh ubuntu
      wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      sh install.sh --unattended
      rm install.sh*

      # Step 2: Setup SSH keys
      cd ~/src
      curl -L https://storage.googleapis.com/us-east-4-anand-files/misc-files/zsh-bootstrap-bionic.tar.gz.enc -H 'Accept: application/octet-stream' --output zsh-bootstrap-bionic.tar.gz.enc
      openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -salt -d -in zsh-bootstrap-bionic.tar.gz.enc -out zsh-bootstrap-bionic.tar.gz
      tar -xvzf zsh-bootstrap-bionic.tar.gz
      mv dotfiles/ssh/* ~/.ssh/
      chmod 700 ~/.ssh/
      ssh -o "StrictHostKeyChecking no" -T git@github.com

      # Step 3: Pull down my .dotfiles repo and setup vim, kube-ps1
      cd ~
      git clone git@github.com:indrayam/dotfiles.git ~/.dotfiles
      cd ~/.dotfiles
      ~/.dotfiles/setup-symlinks-bash.sh
      rm -rf ~/.vim/bundle/Vundle.vim
      git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
      vim -c 'PluginInstall' -c 'qall'
      git clone git@github.com:jonmosco/kube-ps1.git ~/.kube-ps1

      # Step 4: Final touches...
      mkdir -p /home/ubuntu/workspace
      sudo usermod -aG docker $USER
      echo "You're done! Remove this file, exit and log back in to enjoy your new VM"
    path: /home/ubuntu/complete-os-setup.sh
    permissions: '0755'

runcmd:
  - chown -R ubuntu.ubuntu /home/ubuntu
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - add-apt-repository -y ppa:jonathonf/vim
  - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - apt-get update
  - apt-get install -y --allow-unauthenticated docker-ce=$(apt-cache madison docker-ce | grep 19.03 | head -1 | awk '{print $3}')
  - apt-get install -y zsh
  - apt-get install -y vim
  - apt-get install -y kubectl
  - chown -R ubuntu.ubuntu /usr/local/src
  - ln -s /usr/local/src /home/ubuntu/src
  - chown -h ubuntu.ubuntu /home/ubuntu/src

